name: regrid
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h194c533_5
  - aws-c-cal=0.9.8=h346e085_0
  - aws-c-common=0.12.5=hb03c661_1
  - aws-c-compression=0.3.1=h7e655bb_8
  - aws-c-event-stream=0.5.6=h1deb5b9_4
  - aws-c-http=0.10.7=had4b759_1
  - aws-c-io=0.23.2=hbff472d_2
  - aws-c-mqtt=0.13.3=h8ba2272_8
  - aws-c-s3=0.8.6=h493c25d_7
  - aws-c-sdkutils=0.2.4=h7e655bb_3
  - aws-checksums=0.2.7=h7e655bb_4
  - aws-crt-cpp=0.35.0=h719b17a_2
  - aws-sdk-cpp=1.11.606=h522d481_6
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.8.1=pyhd8ed1ab_0
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - brotli-python=1.2.0=py311h7c6b74e_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cartopy=0.25.0=py311hed34c8f_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cf_xarray=0.10.9=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - cftime=1.6.4=py311h0372a8f_2
  - click=8.3.0=pyh707e725_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311hdf67eae_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.1.0=py311h49ec1c0_1
  - dask=2025.11.0=pyhcf101f3_0
  - dask-core=2025.11.0=pyhcf101f3_0
  - debugpy=1.8.17=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distributed=2025.11.0=pyhcf101f3_0
  - esmf=8.9.0=nompi_h8d4c64c_3
  - esmpy=8.9.0=pyhc455866_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - fonttools=4.60.1=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gdal=3.10.3=py311h34ccccb_26
  - geos=3.14.1=h480dda7_0
  - geotiff=1.7.4=h1000f5c_4
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.2=gpl_h7be2006_100
  - libarrow=22.0.0=h99e40f8_3_cpu
  - libarrow-acero=22.0.0=h635bf11_3_cpu
  - libarrow-compute=22.0.0=h8c2c5c3_3_cpu
  - libarrow-dataset=22.0.0=h635bf11_3_cpu
  - libarrow-substrait=22.0.0=h3f74fd7_3_cpu
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcblas=3.9.0=38_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgdal-core=3.10.3=hd23061b_26
  - libgdal-hdf4=3.10.3=ha810028_26
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h4751f2c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=22.0.0=h7376487_3_cpu
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.11.05=h7b12aa8_0
  - librttopo=1.1.0=h46dd2a8_20
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvmlite=0.45.1=py311h41a00d4_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py311h1c460e0_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib-base=3.10.8=py311h0f3be63_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - minizip=4.0.10=h05a5f5f_0
  - msgpack-python=1.1.2=py311hdf67eae_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.11.0=pyhcf101f3_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf-fortran=4.6.2=nompi_h90de81b_102
  - netcdf4=1.7.3=nompi_py311h6623971_100
  - nlohmann_json=3.12.0=h54a6638_1
  - numba=0.62.1=py311h6220fa4_0
  - numpy=2.3.4=py311h2e04523_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hed34c8f_1
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py311h07c5bb8_0
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - proj=9.7.0=hb72c0af_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311haee01d2_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=22.0.0=py311h38be061_0
  - pyarrow-core=22.0.0=py311h342b5a4_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py311h4e6619b_2
  - pyshp=3.0.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - qhull=2020.2=h434a139_5
  - rasterio=1.4.3=py311hf423b78_3
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=hc2a1206_0
  - rioxarray=0.19.0=pyhd8ed1ab_0
  - s2n=1.6.0=h8399546_1
  - scipy=1.16.3=py311h1e13796_0
  - shapely=2.1.2=py311h8a92878_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sparse=0.17.0=pyhcf101f3_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tblib=3.2.2=pyhcf101f3_0
  - tk=8.6.15=h54e0aa7_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py311h49ec1c0_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=17.0.0=py311h49ec1c0_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - xarray=2025.10.1=pyhcf101f3_1
  - xerces-c=3.3.0=h988505b_0
  - xesmf=0.8.10=pyhd8ed1ab_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xyzservices=2025.10.0=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py311haee01d2_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiobotocore==2.25.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - anyio==4.11.0
      - anywidget==0.9.21
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - botocore==1.40.70
      - bounded-pool-executor==0.0.3
      - bqplot==0.12.45
      - branca==0.8.2
      - cachetools==6.2.2
      - charset-normalizer==3.4.4
      - configobj==5.0.9
      - crc32c==2.8
      - defusedxml==0.7.1
      - dengue-africa==0.1.0
      - donfig==0.8.1.post1
      - dotenv==0.9.9
      - earthaccess==0.15.1
      - earthengine-api==1.7.0
      - eerepr==0.1.2
      - fastjsonschema==2.21.2
      - folium==0.20.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - future==1.0.0
      - geemap==0.36.6
      - geocoder==1.38.1
      - geopandas==1.1.1
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.5.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.72.0
      - h11==0.16.0
      - h5netcdf==1.7.3
      - h5py==3.15.1
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - idna==3.11
      - importlib-resources==6.5.2
      - ipyevents==2.0.4
      - ipyfilechooser==0.6.0
      - ipyleaflet==0.20.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jmespath==1.0.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-leaflet==0.20.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - mistune==3.1.4
      - modis-tools==1.2.0
      - multidict==6.7.0
      - multimethod==2.0.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numcodecs==0.16.3
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pathlib-abc==0.5.2
      - plotly==6.4.0
      - pooch==1.8.2
      - pqdm==0.2.0
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - psygnal==0.15.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==1.10.24
      - pyhdf==0.11.6
      - pykdtree==1.4.3
      - pyogrio==0.11.1
      - pyorbital==1.10.2
      - pyperclip==1.11.0
      - pyresample==1.34.2
      - pystac==1.14.1
      - pystac-client==0.9.0
      - python-box==7.3.2
      - python-cmr==0.13.0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - ratelim==0.1.6
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - s3fs==2025.10.0
      - satpy==0.59.0
      - scooby==0.11.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - setuptools==69.2.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - tenacity==9.1.2
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tinynetrc==1.3.1
      - tqdm==4.67.1
      - traittypes==0.2.3
      - trollimage==1.27.0
      - trollsift==1.0.0
      - universal-pathlib==0.3.6
      - uri-template==1.3.0
      - uritemplate==4.2.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - wrapt==1.17.3
      - yarl==1.22.0
      - zarr==3.1.3
prefix: /home/riccardo/miniconda3/envs/regrid
